server:
  port: 9020
spring:
  application:
    name: microservice-message-provdier

  redis:
    database: 0
    cluster:
      nodes: 192.168.101.227:7001,192.168.101.227:7002,192.168.101.227:7003,192.168.101.228:7001,192.168.101.228:7002,192.168.101.228:7003
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

#mq config
#spring.rabbitmq.address: localhost:5672
spring.rabbitmq.host: 192.168.101.109
spring.rabbitmq.port: 5672
spring.rabbitmq.username: javauser
spring.rabbitmq.password: bwoil@123
#spring.rabbitmq.listener.concurrency: 5
#spring.rabbitmq.listener.max-concurrency: 20
#spring.rabbitmq.listener.retry.enabled: true
#spring.rabbitmq.virtual.host: laosiji
spring.rabbitmq.cache.channel.size: 100
#spring.rabbitmq.listener.acknowledge-mode: manual
spring.rabbitmq.listener.publish-returns: true;

#redis config
#redis.host: 192.168.101.227
#redis.port: 7001
#redis.timeout: 0
#redis.pool.max-active: 8
#redis.pool.max-wait: -1
#redis.pool.max-idle: 8
#redis.pool.min-idle: 0
